package uk.org.ca.stub.simulator.rest.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;
import uk.org.ca.stub.simulator.rest.model.ProblemDetailsErrorsInner;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
/**
 * A problem details object compliant with RFC 9457: [Link](https://datatracker.ietf.org/doc/html/rfc9457) 
 */

@Schema(name = "ProblemDetails", description = "A problem details object compliant with RFC 9457: [Link](https://datatracker.ietf.org/doc/html/rfc9457) ")
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-13T15:34:29.284844400Z[Europe/London]", comments = "Generator version: 7.5.0")
public class ProblemDetails {

  private URI type;

  private String title;

  private Integer status;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  private OffsetDateTime datetimestamp;

  private URI asUri;

  @Valid
  private List<@Valid ProblemDetailsErrorsInner> errors = new ArrayList<>();

  public ProblemDetails() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public ProblemDetails(URI type, String title, Integer status, List<@Valid ProblemDetailsErrorsInner> errors) {
    this.type = type;
    this.title = title;
    this.status = status;
    this.errors = errors;
  }

  public ProblemDetails type(URI type) {
    this.type = type;
    return this;
  }

  /**
   * A URI reference that identifies the problem type. see [link](https://datatracker.ietf.org/doc/html/rfc9457#name-type) for details. 
   * @return type
  */
  @NotNull @Valid @Size(max = 1024) 
  @Schema(name = "type", example = "https://example.com/probs/validation-error", description = "A URI reference that identifies the problem type. see [link](https://datatracker.ietf.org/doc/html/rfc9457#name-type) for details. ", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("type")
  public URI getType() {
    return type;
  }

  public void setType(URI type) {
    this.type = type;
  }

  public ProblemDetails title(String title) {
    this.title = title;
    return this;
  }

  /**
   * A short, human-readable summary of the problem type.  see [link](https://datatracker.ietf.org/doc/html/rfc9457#name-title) for details. 
   * @return title
  */
  @NotNull @Size(max = 1024) 
  @Schema(name = "title", example = "Bad Request", description = "A short, human-readable summary of the problem type.  see [link](https://datatracker.ietf.org/doc/html/rfc9457#name-title) for details. ", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ProblemDetails status(Integer status) {
    this.status = status;
    return this;
  }

  /**
   * The HTTP status code generated by the origin server for this error occurrence. see [link](https://datatracker.ietf.org/doc/html/rfc9457#name-status) for details. 
   * minimum: 100
   * maximum: 599
   * @return status
  */
  @NotNull @Min(100) @Max(599) 
  @Schema(name = "status", example = "400", description = "The HTTP status code generated by the origin server for this error occurrence. see [link](https://datatracker.ietf.org/doc/html/rfc9457#name-status) for details. ", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("status")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ProblemDetails datetimestamp(OffsetDateTime datetimestamp) {
    this.datetimestamp = datetimestamp;
    return this;
  }

  /**
   * ISO 8601 timestamp of when the error occurred.  
   * @return timestamp
  */
  @Valid @Size(max = 250) 
  @Schema(name = "datetimestamp", example = "2025-06-26T14:00Z", description = "ISO 8601 timestamp of when the error occurred.  ", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("datetimestamp")
  @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = uk.org.ca.stub.simulator.config.OffsetDateTimeMillisSerializer.class)
  public OffsetDateTime getDatetimestamp() {
    return datetimestamp;
  }

  public void setDatetimestamp(OffsetDateTime datetimestamp) {
    this.datetimestamp = datetimestamp;
  }

  public ProblemDetails asUri(URI asUri) {
    this.asUri = asUri;
    return this;
  }

  /**
   * A URI for PAT refresh. 
   * @return asUri
  */
  @Valid @Size(max = 2048) 
  @Schema(name = "as_uri", example = "https://cda.example.com/ig/pat-refresh", description = "A URI for PAT refresh. ", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("as_uri")
  public URI getAsUri() {
    return asUri;
  }

  public void setAsUri(URI asUri) {
    this.asUri = asUri;
  }

  public ProblemDetails errors(List<@Valid ProblemDetailsErrorsInner> errors) {
    this.errors = errors;
    return this;
  }

  public ProblemDetails addErrorsItem(ProblemDetailsErrorsInner errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Detailed array of errors (extension). Each error item relates to a specific occurrence part of the set of errors  
   * @return errors
  */
  @NotNull @Valid @Size(max = 1000) 
  @Schema(name = "errors", description = "Detailed array of errors (extension). Each error item relates to a specific occurrence part of the set of errors  ", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("errors")
  public List<@Valid ProblemDetailsErrorsInner> getErrors() {
    return errors;
  }

  public void setErrors(List<@Valid ProblemDetailsErrorsInner> errors) {
    this.errors = errors;
  }
    /**
    * A container for additional, undeclared properties.
    * This is a holder for any undeclared properties as specified with
    * the 'additionalProperties' keyword in the OAS document.
    */
    private Map<String, Object> additionalProperties;

    /**
    * Set the additional (undeclared) property with the specified name and value.
    * If the property does not already exist, create it otherwise replace it.
    */
    @JsonAnySetter
    public ProblemDetails putAdditionalProperty(String key, Object value) {
        if (this.additionalProperties == null) {
            this.additionalProperties = new HashMap<String, Object>();
        }
        this.additionalProperties.put(key, value);
        return this;
    }

    /**
    * Return the additional (undeclared) property.
    */
    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    /**
    * Return the additional (undeclared) property with the specified name.
    */
    public Object getAdditionalProperty(String key) {
        if (this.additionalProperties == null) {
            return null;
        }
        return this.additionalProperties.get(key);
    }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProblemDetails problemDetails = (ProblemDetails) o;
    return Objects.equals(this.type, problemDetails.type) &&
        Objects.equals(this.title, problemDetails.title) &&
        Objects.equals(this.status, problemDetails.status) &&
        Objects.equals(this.datetimestamp, problemDetails.datetimestamp) &&
        Objects.equals(this.asUri, problemDetails.asUri) &&
        Objects.equals(this.errors, problemDetails.errors) &&
    Objects.equals(this.additionalProperties, problemDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, title, status, datetimestamp, asUri, errors, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProblemDetails {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    datetimestamp: ").append(toIndentedString(datetimestamp)).append("\n");
    sb.append("    asUri: ").append(toIndentedString(asUri)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

