/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package uk.org.ca.stub.simulator.rest.api;

import uk.org.ca.stub.simulator.rest.model.StubConfiguration;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-19T09:56:51.631872900Z[Europe/London]", comments = "Generator version: 7.5.0")
@Validated
@Tag(name = "configuration", description = "the configuration API")
public interface ConfigurationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /configuration : Configure stubbed responses for selected endpoints
     * Configure error stubs for endpoints. Send an empty array to clear all configurations. 
     *
     * @param stubConfiguration  (required)
     * @return Configuration accepted (status code 204)
     */
    @Operation(
        operationId = "configurationPost",
        summary = "Configure stubbed responses for selected endpoints",
        description = "Configure error stubs for endpoints. Send an empty array to clear all configurations. ",
        responses = {
            @ApiResponse(responseCode = "204", description = "Configuration accepted")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/configuration",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> configurationPost(
        @Parameter(name = "StubConfiguration", description = "", required = true) @Valid@Size(min = 0, max = 6)  @RequestBody List<@Valid StubConfiguration> stubConfiguration
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
